server:
  port: 8188

spring:
  servlet:
    #文件上传配置
    multipart:
      max-file-size: 3MB
      max-request-size: 6MB
  mvc:
    pathmatch:
      #swagger所需要的配置
      matching-strategy: ant_path_matcher
  application:
    name: security-jwt2
    #这里我们使用的是mysql8.0的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.184.123:3308/security-jwt-db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # spring-data-redis配置
  redis:
    database: 2
    host: 192.168.184.123
    port: 6379
    #配置lettuce连接池，大幅提高性能（如果不进行配置，则默认是不使用连接池,只有进行了下面的配置，连接池才会生效）
    lettuce:
      pool:
        #min-idle建议配置：0
        min-idle: 0
        #max-idle建议配置：cpu核心数*2，由于我们cpu是i5-9300H，是4核cpu，所以建议设置8
        max-idle: 8
        #max-active建议配置：大于等于cpu核心数*2，也是推荐设置8
        max-active: 8
        #使用redis默认值即可：-1
        max-wait: -1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml


# 自定义jwt配置
jwt:
  config:
    # accessToken的名称（和前端存储在localstorage的token名称一致）
    access-token-name: accessToken
    # accessToken密钥
    access-token-key: accessToken-key
    # 10800000毫秒（=3小时）过期
    access-token-expired: 10800000
    # refreshToken的名称（和前端存储在localstorage的token名称一致）
    refresh-token-name: refreshToken
    # refreshToken密钥
    refresh-token-key: refreshToken-key
    # 21600000毫秒（=6小时）过期
    refresh-token-expired: 21600000
    # token最多刷新次数
    max-refresh-count: 5
    # accessToken黑名单key前缀
    access-token-blacklist-prefix: accessBlack_
    # refreshToken黑名单key前缀
    refresh-token-blacklist-prefix: refreshBlack_

#七牛云oss配置
qiniu:
  # 密钥管理的AK
  accessKey: xPu-62ptMpg-kolm4nPVcvWgUnK1EZgu27ffKpBE
  #密钥管理的SK
  secretKey: gDxkqTu7i7BBgbsvoQ7h4bmE5m16aRyHXyQ1Zc6D
  #指定我们文件上传的存储空间名称
  bucket: java-qiniu
  # 七牛云图片服务器域名（有效期30天，过期可以重新创建新的存储空间）
  ossUrl: http://rjc4vwz0g.hn-bkt.clouddn.com/